# Python from Scratch
## Computer Vision and Image Processing - Lecture 1

## Introduction

Python is a programming language very widespread in the scientific communuty and one of the most required when you want to apply for a Computer Science position. Python is a interpreted, high level, dinamically typed language. 

Python uses whitespace indentation, rather than curly brackets or keywords, to delimit blocks. An increase in indentation comes after certain statements; a decrease in indentation signifies the end of the current block.

Two main versions of Python: Python 2.x and Python 3.x are available. 
The two version have several features in common, the two version are not fully compatibile between each other and a Python 2.x program may not work for Python 3.x and viceversa.

In this course we will use Python 3.x since Python 2.x won’t be supported anymore starting from 2020, but many programmers are still using it.

You can check your Python version at the command line by running `python --version`.

In this lecture, we will cover:

* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting

## Basic Data types

As we said before, Python is a dynamically typed language. This means that we are not forced to explicit the type of each variable, since the compiler is smart enough to understand the type by himself.

### Numbers and Mathematical operation

In [10]:
x = 3
print(x, type(x)) 
print("Addition: ", x + 1)
print("Subtraction: ", x - 1)
print("Multiplication: ", x * 2)
print("Exponentiation: ", x ** 2)

# Support += syntax
x += 1
print("x+=1 -> x =", x)
x *= 2
print("x*=2 -> x =", x)

x = 3  # int
y = 2. # float
div = x / y
print("Division: ", div, type(div))
floor_div = x // y
print("Floored division: ", floor_div, type(floor_div))
mod = x % y
print("Module ", mod, type(mod))

3 <class 'int'>
Addition:  4
Subtraction:  2
Multiplication:  6
Exponentiation:  9
x+=1 -> x = 4
x*=2 -> x = 8
Division:  1.5 <class 'float'>
Floored division:  1.0 <class 'float'>
Module  1.0 <class 'float'>


### Casting types
Sometimes we need to change from a type to another. To do so, we can cast the type.

In [23]:
d = int(x / y)
print(d, type(d))
d = float(int(x / y))
print(d, type(d))

1 <class 'int'>
1.0 <class 'float'>


### Booleans

In [29]:
t, f = True, False
print("T, F: ", t, f, type(t))
print("Logical T AND F: ", t and f)
print("Logical T OR F: ", t or f)
print("Logical NOT T: ", not t)
print("Logical T XOR F: ", t != f)

T, F:  True False <class 'bool'>
Logical T AND F:  False
Logical T OR F:  True
Logical NOT T:  False
Logical T XOR F:  True


### Strings

In [30]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print(hello, len(hello)) ### print string and lenght of string
hw = hello + ' ' + world  # String concatenation
print(hw) # prints "hello world"

hello 5
hello world


Several useful methods for handling strings are implemented:

In [31]:
s = "  hello world"
print(s.upper())
print(s.replace('l','llll'))
print(s.strip())

  HELLO WORLD
  hellllllllo worlllld
hello world


Lot of times we need to format a string to improve the readability.

We can format our string using the format method of strings.

In [37]:
s = "World"
print("Hello {}".format(s)) # Insert string variable
n = 1.2345678
print(n)
print("4 decimal digits {:.4f}".format(n)) # Adjusting the number of number digits to show


Hello World
1.2345678
4 decimal digits 1.2346


You can find a list of all string methods in the [documentation](https://docs.python.org/3.5/library/stdtypes.html#string-methods).

## Containers

### Lists

Lists in python ca contain element of different type. Several built-in methods are provided by python to manage lists

In [49]:
lst = [0, 1, 2, "hi"]   # Create a list, python lists can contain element of different types.
print(lst, lst[2], lst[-1]) # Negative indices count from the end of the list; prints "ciao"

list_slice = lst[2:4] # Access a slice from the list. First index included, last index excluded.
print(list_slice)

lst.append('bar') # append a new element to the list
print(lst)

l = lst.pop() # Remove and return the last element of the list
print(l, lst)

[0, 1, 2, 'hi'] 2 hi
[2, 'hi']
[0, 1, 2, 'hi', 'bar']
bar [0, 1, 2, 'hi']


### Dictionaries

Dictionaries contain couples of (key,value). The key-set contain unique objects.

In [54]:
d = {"Mickey Mouse" : "Minnie", "Donald Duck": "Daisy"}
print(d["Mickey Mouse"]) # Get an entry from a dictionary
print("Mickey Mouse" in d)

d["Goofy"]= "Pluto" # Add element to dictionary
print(d)


Minnie
True
{'Mickey Mouse': 'Minnie', 'Donald Duck': 'Daisy', 'Goofy': 'Pluto'}


### Set
A set is a list of unique objects. Python will ignore duplicate items.

In [65]:
st = {'cat', 'dog'}
st.add('bird')
print(st)
st.add('bird') # Ignore duplicate item
print(st)


lst = ['dog', 'dog', 'dog', 'fish']
st = set(lst) # Casting list to set will delete duplicate items
print(st)

{'dog', 'bird', 'cat'}
{'dog', 'bird', 'cat'}
{'dog', 'fish'}


### Tuples
A tuple is an (immutable) ordered list of values.

In [67]:
t = (5, 4)
print(t)

(5, 4)


In [68]:
t[1]=2 # Cannot change the value, exception arise

TypeError: 'tuple' object does not support item assignment

## Statements

### _IF_

In [45]:
a = "ciao"
b = "ciao"
x = 1
y = 2

if a == b:
    print("The two strings are equal!")
else: 
    print("The two strings are different!")

if x > y:
    print("x greater than y")
elif x == y:
    print("x equal to y")
else:
    print("x smaller than y")

The two strings are equal!
x smaller than y


### _FOR_

In [61]:
subjects = ['math', 'history', 'physics']

for sub in subjects: # Iterate among the elemets of a list
    if sub != 'math':
        print(sub)

d = {"Mickey Mouse" : "Minnie", "Donald Duck": "Daisy"}
for ch in d: # Iterate among the elemets of a dictionary
    print("Key: ", ch, ", Value: ", d[ch])

lst = []
for i in range(0,5): # Iterate from 0 to 4
    print(i)
    lst.append(i)

print(lst)
squares = [x ** 2 for x in lst] # List Comprehension, simpler way to compute lists
squares_even = [x ** 2 for x in lst if x % 2 == 0] # List Comprehension, simpler way to compute lists

print("Squares", squares)
print("Square of even elemets ", squares_even)

history
physics
Key:  Mickey Mouse , Value:  Minnie
Key:  Donald Duck , Value:  Daisy
0
1
2
3
4
[0, 1, 2, 3, 4]
Squares [0, 1, 4, 9, 16]
Square of even elemets  [0, 4, 16]


### _WHILE_

In [69]:
vec = [1,2,3,4,5,6]
cnt = 0
while cnt < len(vec):
    print(vec[cnt])
    cnt += 1

1
2
3
4
5
6


## Functions

Python functions are defined using the `def` keyword. For example:

In [80]:
def diff(x, y, absolute_value=False): #absloute_value is an optional argument with default=False
    if absolute_value:
        return abs(x - y)
    else:
        return x -y

lst = [1,4,6,5,11,7]
for idx, l in enumerate(lst):
    if idx != 0:
        dff = diff(lst[idx], lst[idx -1], absolute_value=True)
        abs_dff = diff(lst[idx], lst[idx -1], absolute_value=False) 
        print(dff, abs_dff)

3 3
2 2
1 -1
6 6
4 -4


## Classes

The syntax for defining classes in Python is straightforward:

In [13]:
class Animal:
    # Constructor
    def __init__(self, name):
        self.name = name 

class Cat(Animal):
    def __init__(self):
        super(Cat,self).__init__("cat")
    def greet(self):
        print("Hi, I am a ", self.name)
        

cat_instance = Cat()
cat_instance.greet()

Hi, I am a  cat


## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.
To use Numpy, we first need to import the `numpy` package:

In [43]:
import numpy as np

### Arrays

An array object represents a multidimensional, homogeneous array of items of the same data-type. Numpy array can be accessed by index into square brackets.

In [20]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a) 

b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

print(b.shape)                 
print(b[0, 0], b[0, 1], b[1, 0])

# Numpy have methods to create several defaults arrays

print("Zeros array")
a = np.zeros((2,2))  # Create an array of all zeros
print(a)
print("Ones array")
b = np.ones((1,2))   # Create an array of all ones
print(b)
print("Full array")
c = np.full((2,2), 7) # Create an array of constants (7)
print(c)
print("Identity matrix")
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)
print("Random matrix")
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4
Zeros array
[[0. 0.]
 [0. 0.]]
Ones array
[[1. 1.]]
Full array
[[7 7]
 [7 7]]
Identity matrix
[[1. 0.]
 [0. 1.]]
Random matrix
[[0.57689252 0.16307264]
 [0.36447272 0.67965541]]


All the items of a numpy array have the same type. When you create an array, numpy guess which datatype fix better to your data, but you can set it when creating the numpy array. 

In [29]:
a = np.array([1, 2])                   # Let numpy choose the datatype
b = np.array([1.0, 2.0])               # Let numpy choose the datatype
c = np.array([1, 2], dtype=np.float32) #Force a particular datatype
d = np.array([1, 2], dtype=np.int64)   #Force a particular datatype
print(a)
print(b)
print(c)
print(d)

[1 2]
[1. 2.]
[1. 2.]
[1 2]


Numpy offers several ways to index into arrays.
Similar to lists numpy arrays can be sliced specifing a slice for each dimension of the array.

In [22]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array share the same memory area of the original array. Modifing it will modify also the original array

In [25]:
b[0,0] = 100
print(a[0,1])

100


Integer arrays can be used as indexes of other arrays

In [216]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print a[np.arange(4), b]  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [223]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.
print(idx)
print(a[idx])

[[False False]
 [ True  True]
 [ True  True]]


### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [35]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("Elementwise sum")
print(x + y)
print(np.add(x, y))
print("Elementwise difference")
print(x - y)
print(np.subtract(x, y))
print("Elementwise product")
print(x * y)
print(np.multiply(x, y))
print("Elementwise division")
print(x / y)
print(np.divide(x, y))


Elementwise sum
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
Elementwise difference
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
Elementwise product
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
Elementwise division
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Moreover, several mathematical operation between arrays are implemented in Numpy.

In [38]:
print("Elementwise square root")
print(np.sqrt(x))
print("Matrix / vector product")
print(x.dot(y))
print(np.dot(x, y))

Elementwise square root
[[1.         1.41421356]
 [1.73205081 2.        ]]
Matrix / vector product
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


Numpy provides several reduction functions.

In [39]:
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7

print(np.mean(x))
print(np.mean(x, axis= 0))
print(np.mean(x, axis=1))

10.0
[4. 6.]
[3. 7.]
2.5
[2. 3.]
[1.5 3.5]


Moreover, Numpy provides function to modify the shape of arrays.

In [42]:
print(x)
print("Transpose")
print(x.T)
print("Reshape Shape source: ", x.shape, "Shape target: ", (1,4))
print(x.reshape([1,4]))

[[1. 2.]
 [3. 4.]]
Transpose
[[1. 3.]
 [2. 4.]]
Reshape Shape source:  (2, 2) Shape target:  (1, 4)
[[1. 2. 3. 4.]]


You can find the full list functions provided by numpy in the [documentation](https://docs.scipy.org/doc/numpy-1.17.0/reference/).

### Broadcasting

Broadcasting is the mechanism used by numpy to deal with arrays of different shapes during mathematical operations. This can be extremely useful in a variety of situation and expedite the computation time in matrix operations. Below an example of sum between arrays with different shapes implemented with for cycle and without broadcasting: 

In [54]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([0, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 1  2  4]
 [ 4  5  7]
 [ 7  8 10]
 [10 11 13]]


If the matrix _x_ is very large, computing loop cycles in Python is really slow. 
Another way to implement the same problem improving the perfomances could be:

In [55]:
print("x= \n", x)
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print("vv = \n", vv)
y = x + vv
print("x + vv =\n" , y)

x= 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
vv = 
 [[0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]]
x + vv =
 [[ 1  2  4]
 [ 4  5  7]
 [ 7  8 10]
 [10 11 13]]


This version is computationally cheap but the code is not straightforward to write. Broadcasting allows to do it extremely easy automatically adressing shape compability problems.

In [57]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([0, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 1  2  4]
 [ 4  5  7]
 [ 7  8 10]
 [10 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Example: multiply by a scalar:

In [60]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


_Broadcasting_ two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension